#!/bin/bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Script to manage speaker volume on Archcraft.

# Icons
iDIR='/home/anastasia/.config/dunst/icons/'
notify_cmd='dunstify -u low -h string:x-dunst-stack-tag:obvolume -t 1500'

# Get Volume
get_volume() {
	echo "`pulsemixer --get-volume | cut -d' ' -f1`"
}

# Get icons
get_icon() {
	current="$(get_volume)"
	if [[ "$current" -eq "0" ]]; then
		icon="$iDIR/volume-mute.svg"
	elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
		icon="$iDIR/volume-low.svg"
	elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
		icon="$iDIR/volume-medium.svg"
	elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
		icon="$iDIR/volume-high.svg"
	fi
}

# Notify
notify_user() {
	${notify_cmd} -i "$icon" "Volume : $(get_volume)%"
}

# Increase Volume
inc_volume() {
	[[ `pulsemixer --get-mute` == 1 ]] && pulsemixer --unmute
	pulsemixer --max-volume 100 --change-volume +5 && get_icon && notify_user
}

# Increase Volume by 1
inc_volume_fine() {
	[[ `pulsemixer --get-mute` == 1 ]] && pulsemixer --unmute
	pulsemixer --max-volume 100 --change-volume +1 && get_icon && notify_user
}

# Decrease Volume
dec_volume() {
	[[ `pulsemixer --get-mute` == 1 ]] && pulsemixer --unmute
	pulsemixer --max-volume 100 --change-volume -5 && get_icon && notify_user
}

# Decrease Volume by 1
dec_volume_fine() {
	[[ `pulsemixer --get-mute` == 1 ]] && pulsemixer --unmute
	pulsemixer --max-volume 100 --change-volume -1 && get_icon && notify_user
}

# Toggle Mute
toggle_mute() {
	if [[ `pulsemixer --get-mute` == 0 ]]; then
		pulsemixer --toggle-mute && ${notify_cmd} -i "$iDIR/volume-mute.svg" "Mute"
	else
		pulsemixer --toggle-mute && get_icon && ${notify_cmd} -i "$icon" "Unmute"
	fi
}

# Toggle Mic
toggle_mic() {
	ID="`pulsemixer --list-sources | grep 'Default' | cut -d',' -f1 | cut -d' ' -f3`"
	if [[ `pulsemixer --id $ID --get-mute` == 0 ]]; then
		pulsemixer --id ${ID} --toggle-mute && ${notify_cmd} -i "$iDIR/microphone-off.svg" "Microphone Switched OFF"
	else
		pulsemixer --id ${ID} --toggle-mute && ${notify_cmd} -i "$iDIR/microphone.svg" "Microphone Switched ON"
	fi
}

# Execute accordingly
if [[ -x `which pulsemixer` ]]; then
	if [[ "$1" == "--get" ]]; then
		get_volume
	elif [[ "$1" == "--inc" ]]; then
		inc_volume
  elif [[ "$1" == "--inc-fine" ]]; then
		inc_volume_fine
	elif [[ "$1" == "--dec" ]]; then
		dec_volume
  elif [[ "$1" == "--dec-fine" ]]; then
		dec_volume_fine
	elif [[ "$1" == "--toggle" ]]; then
		toggle_mute
	elif [[ "$1" == "--toggle-mic" ]]; then
		toggle_mic
	else
		echo $(get_volume)%
	fi
else
	${notify_cmd} "'pulsemixer' is not installed."
fi
